version: '3.7'

services:
  push-sms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/push-sms
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/push-sms
    working_dir: /var/www/push-sms
    networks:
      - internal
      - traefik_default

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28
  traefik_default:
    external: true
